name: PullRequestTest

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Permissions to mvnw
        run: chmod +x mvnw

      - name: Test
        run: ./mvnw test